/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FruitFruitIdRouteImport } from './routes/fruit.$fruitId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FruitFruitIdRoute = FruitFruitIdRouteImport.update({
  id: '/fruit/$fruitId',
  path: '/fruit/$fruitId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/fruit/$fruitId': typeof FruitFruitIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/fruit/$fruitId': typeof FruitFruitIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/fruit/$fruitId': typeof FruitFruitIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/fruit/$fruitId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/fruit/$fruitId'
  id: '__root__' | '/' | '/fruit/$fruitId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FruitFruitIdRoute: typeof FruitFruitIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fruit/$fruitId': {
      id: '/fruit/$fruitId'
      path: '/fruit/$fruitId'
      fullPath: '/fruit/$fruitId'
      preLoaderRoute: typeof FruitFruitIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FruitFruitIdRoute: FruitFruitIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
